Fixed doc typos re: @Jsonb(De)Serializer
jakartaee/jsonb-api pull request #183
Opened 2019-08-21 09:41 UTC by mkarg

Partial fix of #70 (JavaDocs only)

Unfortunately I could only fix the JavaDocs, as there is just boilerplate for the actual spec.

2019-08-21 09:43 UTC, mkarg commented
I marked this PR as a **draft**, as the spec source is not contained. Please tell me if I shall keep it in draft state until the spec source is available, or whether I shall turn it in a real PR so you could merge it. Thanks. :-)

2019-08-27 16:33 UTC, m0mus commented
@aguibert You better ask Eclipse folks. They need to do some legal checks before allowing us using the old spec text.

2019-08-27 18:06 UTC, mkarg commented
@m0mus Did EF already ask you for your approval of the spec? I was asked weeks ago and it seems nothing happend so far.

So how to proceed? Keep the PR in draft state until we have the OK from the EF, or merge this PR, keep the issue open, and create another PR for the spec change?

2019-08-28 10:58 UTC, m0mus commented
@mkarg No, I didn't have any request from EF regarding the spec. I suppose that it will happen after Jakarta EE 8 release.

2019-10-01 16:31 UTC, rmannibucau approved these changes

2025-03-04 07:38 UTC, jungm commented
Spec document has been merged a long time ago (https://github.com/jakartaee/jsonb-api/commit/3b879d75bf969d9321ac9b3b94695279bce7a70f), can we get this PR merged or possibly even extended to also fix the spec?

2026-05-26 19:43 UTC, KyleAure requested changes

2026-05-26 19:43 UTC, KyleAure commented on docs/src/docs/user-guide.adoc
> +// Also configurable with @JsonbTypeSerializer / @JsonbTypeDeSerializer on properties and class.
```suggestion
// Also configurable with @JsonbTypeSerializer / @JsonbTypeDeserializer on properties and class.
```

2026-05-26 19:44 UTC, KyleAure commented
@mkarg - please resolve the merge conflicts and see my review above.  I'd like to get this merged.

2026-09-16 14:47 UTC, closed without merging